# Generated by Django 4.2.5 on 2023-09-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='company',
            new_name='company_id',
        ),
    ]
