# Generated by Django 4.2.5 on 2023-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0003_rename_company_id_jobposting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('user_id', 'job_posting')},
        ),
    ]
