# Generated by Django 4.2.5 on 2023-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpostings', '0004_alter_applicant_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
